/**
 * Section Image Configuration
 *
 * Maps moduleNumber → sectionSlug → image(s) to insert near h3/h4 headings.
 * Section slugs match the IDs generated by extract-toc.ts (lowercase, hyphens).
 *
 * Image files live in: public/images/modules/module-{N}/
 * Recommended: 1200px wide, 16:9 aspect, WebP or JPEG format.
 */

export interface SectionImage {
  src: string;
  alt: string;
  caption?: string;
  position?: 'before' | 'after'; // default: 'after'
  float?: 'right'; // float image alongside text
  size?: 'small';
}

export const sectionImages: Record<number, Record<string, SectionImage[]>> = {
  1: {
    // h4-level placements (images appear after the specific h4 heading)
    'construction-stakeout-and-grade-control': [
      {
        src: '/images/modules/module-1/construction-stakeout-and-grade-control.png',
        alt: 'Construction stakeout showing robotic total station, batter boards, string lines, offset stakes, plumb bob, and RTK GPS unit on a residential building site',
        caption: 'Key surveying tools: Robotic Total Station, RTK GPS, batter boards, offset stakes, string lines, and plumb bob',
      },
    ],
    'grubbing-and-organic-material-removal': [
      {
        src: '/images/modules/module-1/grubbing-and-organic-material-removal.png',
        alt: 'Grubbing and organic material removal during site preparation, showing heavy equipment clearing vegetation and root systems',
        caption: 'Site preparation: Grubbing and organic material removal before grading begins',
      },
    ],
    'temporary-utilities-installation': [
      {
        src: '/images/modules/module-1/temporary-utilities-installation.png',
        alt: 'Temporary electrical pole, panel, and water connection installation for construction site utilities',
        caption: 'Temporary utilities: Electrical pole and panel installation for construction use',
      },
    ],
    'site-logistics-planning-and-optimization': [
      {
        src: '/images/modules/module-1/site-logistics-planning-and-optimization.png',
        alt: 'Site logistics planning showing material staging areas, equipment positioning, access routes, and workflow optimization on a construction site',
        caption: 'Site logistics: Planning material staging, equipment access, and workflow optimization',
      },
    ],
  },
  2: {
    // Image 1: After the Survey Stake heading (above section content)
    '1-survey-stake-interpretation-and-layout-verification': [
      {
        src: '/images/modules/module-2/Survey_Stakes_And_Layout_Verification.png',
        alt: 'Survey stakes and layout verification on a foundation construction site, showing offset stakes, string lines, and grade markers',
        caption: 'Survey stakes and layout verification for foundation positioning',
      },
    ],
    // Image 2: Before the Foundation Wall Construction h3 section
    'foundation-wall-construction': [
      {
        src: '/images/modules/module-2/Footing_Construction.png',
        alt: 'Footing construction showing reinforced concrete footings with rebar cage, form boards, and grade stakes on excavated foundation site',
        caption: 'Footing construction: Reinforced concrete footings ready for foundation walls',
        position: 'before',
      },
    ],
    // Image 3: Before Step 4: Concrete Placement and Vibration
    'step-4-concrete-placement-and-vibration': [
      {
        src: '/images/modules/module-2/Vibrating_Stem_Wall.png',
        alt: 'Concrete vibration of stem wall forms using internal vibrator to consolidate concrete and eliminate honeycombing',
        caption: 'Concrete placement and vibration of foundation stem wall forms',
        position: 'before',
      },
    ],
    // Image 4: Before Step 4: Protection Board and Backfill Preparation
    'step-4-protection-board-and-backfill-preparation': [
      {
        src: '/images/modules/module-2/Protection_Board_and_Backfill_Preparation.png',
        alt: 'Foundation waterproofing protection board installation and backfill preparation showing drainage mat, dimple board, and gravel backfill',
        caption: 'Protection board installation and backfill preparation for foundation waterproofing',
        position: 'before',
      },
    ],
    // Image 5: After the Foundation/Under-Slab Inspection heading
    'inspection-checkpoint-foundation-and-under-slab-plumbing': [
      {
        src: '/images/modules/module-2/Foundation_Wall_Inspection.png',
        alt: 'Foundation wall inspection showing inspector verifying rebar placement, form alignment, anchor bolt positioning, and concrete quality',
        caption: 'Foundation and under-slab plumbing inspection checkpoint',
      },
    ],
  },
  3: {
    // Image 1: After Floor Joist Installation h3 (before IRC Framing Requirements callout)
    'floor-joist-installation': [
      {
        src: '/images/modules/module-3/Floor_Joist_Installation.png',
        alt: 'Floor joist installation showing dimensional lumber and engineered I-joists with proper spacing, blocking, and bearing connections',
        caption: 'Floor joist installation: Proper spacing, blocking, and bearing connections',
      },
    ],
    // Image 2: Before Installation Best Practices h4
    'installation-best-practices-and-performance-standards': [
      {
        src: '/images/modules/module-3/Installation_Best_Practices.png',
        alt: 'Subfloor installation best practices showing adhesive application, fastener patterns, and panel layout for optimal performance',
        caption: 'Installation best practices: Adhesive application and fastener patterns for subfloor performance',
        position: 'before',
      },
    ],
    // Image 3: Before Wall Assembly Process h3
    'wall-assembly-process-and-quality-standards': [
      {
        src: '/images/modules/module-3/Wall_Assembly.png',
        alt: 'Wall framing assembly showing stud layout, top and bottom plates, corner assemblies, and temporary bracing on a residential construction site',
        caption: 'Wall assembly: Stud layout, plate connections, and temporary bracing',
        position: 'before',
      },
    ],
    // Image 4: Before Preparing for Next Steps h3
    'preparing-for-next-steps': [
      {
        src: '/images/modules/module-3/Module_Summary.png',
        alt: 'Completed residential framing showing floor system, wall framing, and header installations ready for roof framing',
        caption: 'Module summary: Completed framing structure ready for next construction phase',
        position: 'before',
      },
    ],
  },
  4: {
    // Image 1: After Traditional vs. Synthetic Underlayment h4
    'traditional-vs-synthetic-underlayment': [
      {
        src: '/images/modules/module-4/Underlayment_Selection_and_Installation_Protocols.png',
        alt: 'Comparison of traditional felt and synthetic roofing underlayment materials showing installation methods and performance characteristics',
        caption: 'Underlayment selection: Traditional felt vs. synthetic underlayment comparison',
      },
    ],
    // Image 2: After ⚠️ Ice Dam Formation Process h4
    'ice-dam-formation-process': [
      {
        src: '/images/modules/module-4/Ice_Dam_Formation_Process.png',
        alt: 'Diagram showing ice dam formation process on a roof, including heat loss, snowmelt, refreezing at eaves, and water backup under shingles',
        caption: 'Ice dam formation: Heat loss causes snowmelt and refreezing at eaves',
      },
    ],
    // Image 3: After Roof Ventilation Requirements and Thermal Performance h3
    'roof-ventilation-requirements-and-thermal-performance': [
      {
        src: '/images/modules/module-4/Roofing_Ventilation.png',
        alt: 'Roof ventilation system showing soffit vents, ridge vents, baffles, and airflow patterns for proper attic ventilation and thermal performance',
        caption: 'Roof ventilation: Balanced intake and exhaust airflow for thermal performance',
      },
    ],
    // Image 4: After Critical Installation Sequence h4
    'critical-installation-sequence': [
      {
        src: '/images/modules/module-4/Window_Flashing_Detail.png',
        alt: 'Window flashing installation detail showing sill pan, jamb flashing, head flashing, and weather-resistive barrier integration sequence',
        caption: 'Window flashing detail: Proper installation sequence for weather-tight openings',
      },
    ],
    // Image 5: Before Critical Vinyl Siding Installation Rules h4
    'critical-vinyl-siding-installation-rules': [
      {
        src: '/images/modules/module-4/Vinyl_Siding_Buckling.png',
        alt: 'Vinyl siding buckling and thermal distortion caused by improper fastener installation and insufficient expansion gaps',
        caption: 'Vinyl siding buckling: Result of improper fastener clearance and expansion gaps',
        position: 'before',
      },
    ],
    // Image 6: After ✓ Look-Ahead Scheduling Priorities h4
    'look-ahead-scheduling-priorities': [
      {
        src: '/images/modules/module-4/Critical_Path_Scheduling.png',
        alt: 'Critical path scheduling diagram showing exterior finish trade sequencing, weather windows, and multi-trade coordination timeline',
        caption: 'Critical path scheduling: Trade sequencing and weather-responsive planning',
      },
    ],
  },
  5: {
    // Image 1: After HVAC Load Calculation Requirements callout (end of Equipment Installation section)
    'ductwork-installation-and-sealing-requirements': [
      {
        src: '/images/modules/module-5/HVAC_Load_Calcs_Reqs.png',
        alt: 'HVAC load calculation requirements showing Manual J calculations, equipment sizing parameters, and system design specifications',
        caption: 'HVAC load calculation requirements: Manual J sizing and system design standards',
        position: 'before',
      },
    ],
    // Image 2: After Combustion Air and Venting Requirements h3 heading
    'combustion-air-and-venting-requirements': [
      {
        src: '/images/modules/module-5/Combustion_Air_And_Venting_Reqs.png',
        alt: 'Combustion air and venting requirements showing proper clearances, vent sizing, and draft configurations for gas appliances',
        caption: 'Combustion air and venting: Proper clearances and vent configurations',
      },
    ],
    // Image 3: After Water Supply Sizing Standards callout (end of Water Service section)
    'water-supply-piping-materials-and-installation': [
      {
        src: '/images/modules/module-5/Water_Supply_Sizing_Standards.png',
        alt: 'Water supply sizing standards showing pipe diameter calculations, fixture unit counts, and pressure requirements',
        caption: 'Water supply sizing standards: Pipe diameter and fixture unit calculations',
        position: 'before',
      },
    ],
    // Image 4: After Drain, Waste, and Vent System Design h3, before Plumbing Vent callout
    'drain-waste-and-vent-system-design': [
      {
        src: '/images/modules/module-5/Drainage.jpg',
        alt: 'Drain, waste, and vent system design showing pipe routing, slope requirements, cleanout locations, and trap configurations',
        caption: 'DWV system design: Drainage pipe routing and slope requirements',
      },
    ],
    // Image 5: End of Venting section, before Fixture Rough-In
    'fixture-rough-in-and-dimensional-standards': [
      {
        src: '/images/modules/module-5/Venting.jpg',
        alt: 'Plumbing vent system showing vent stack routing, AAV placement, and roof penetration details',
        caption: 'Venting system: Vent stack routing and configuration details',
        position: 'before',
      },
    ],
    // Image 6: End of Pressure Testing section, before ⚡ Electrical h2
    'electrical-contractor-responsibilities-and-system-design': [
      {
        src: '/images/modules/module-5/Pressure_Testing_And_Validation.png',
        alt: 'Pressure testing and system validation showing gauge readings, test procedures, and acceptance criteria for plumbing systems',
        caption: 'Pressure testing and validation: System integrity verification procedures',
        position: 'before',
      },
    ],
    // Image 7: After Service Panel Installation h3 heading
    'service-panel-installation-and-grounding-system': [
      {
        src: '/images/modules/module-5/Service_Panel_Installation.png',
        alt: 'Service panel installation showing panel mounting, grounding electrode system, neutral-ground bond, and circuit breaker layout',
        caption: 'Service panel installation: Panel mounting and grounding system configuration',
      },
    ],
  },
  6: {
    // Image 1: After Batt Insulation h4 heading
    'batt-insulation-installation-and-quality-control': [
      {
        src: '/images/modules/module-6/Batt_Insulation.png',
        alt: 'Batt insulation installation showing proper fit between studs, vapor barrier placement, and quality control techniques',
        caption: 'Batt insulation: Proper installation between wall studs with full cavity coverage',
      },
    ],
    // Image 2: After Blown-In Insulation h4 heading
    'blown-in-insulation-systems-and-application-methodology': [
      {
        src: '/images/modules/module-6/Blown_Insulation.png',
        alt: 'Blown-in insulation application showing cellulose or fiberglass being installed in attic and wall cavities',
        caption: 'Blown-in insulation: Dense-pack and loose-fill application methods',
      },
    ],
    // Image 3: After Spray Foam Insulation h4 heading
    'spray-foam-insulation-technology-and-application-science': [
      {
        src: '/images/modules/module-6/Sprayfoam_Insulation.png',
        alt: 'Spray foam insulation application showing open-cell and closed-cell foam being applied to wall cavities and rim joists',
        caption: 'Spray foam insulation: Open-cell and closed-cell application technology',
      },
    ],
    // Image 4: After Drywall Hanging h4 heading
    'drywall-hanging-techniques-and-attachment-specifications': [
      {
        src: '/images/modules/module-6/Hang_Drywall.png',
        alt: 'Drywall hanging techniques showing proper sheet orientation, screw patterns, and ceiling-first installation sequence',
        caption: 'Drywall hanging: Sheet orientation, fastener spacing, and installation sequence',
      },
    ],
    // Image 5: After Taping Process h4 heading
    'taping-process-and-first-coat-application': [
      {
        src: '/images/modules/module-6/Drywall_Tape_And_Mud.webp',
        alt: 'Drywall taping and first coat application showing paper tape embedding, joint compound application, and finishing tools',
        caption: 'Taping and first coat: Paper tape embedding and joint compound application',
      },
    ],
    // Image 6: End of Insulation Inspection section, before Energy Code
    'energy-code-compliance-and-blower-door-testing': [
      {
        src: '/images/modules/module-6/Insulation_Check.png',
        alt: 'Insulation inspection showing thermal envelope verification, ventilation baffle clearance check, and R-value compliance testing',
        caption: 'Insulation inspection: Thermal envelope verification and compliance check',
        position: 'before',
      },
    ],
    // Image 7: End of Energy Code section, before Construction Manager h3
    'construction-manager-project-coordination-and-quality-assurance': [
      {
        src: '/images/modules/module-6/Blower_Door_test.png',
        alt: 'Blower door test setup showing fan installation, pressure gauge readings, and air leakage measurement for energy code compliance',
        caption: 'Blower door test: Air leakage measurement for energy code compliance verification',
        position: 'before',
      },
    ],
  },
  7: {
    // Images 1-2: Side-by-side after Primer Application and Substrate Sealing h4
    'primer-application-and-substrate-sealing': [
      {
        src: '/images/modules/module-7/01_Spraying_PVA_Primer.png',
        alt: 'Spraying PVA primer onto drywall surfaces for proper sealing and paint adhesion',
        caption: 'Spraying PVA primer for uniform surface sealing',
      },
      {
        src: '/images/modules/module-7/02_Backrolling_PVA_Primer.png',
        alt: 'Back-rolling PVA primer to ensure even coverage and penetration into drywall surface',
        caption: 'Back-rolling primer for complete coverage and adhesion',
      },
    ],
    // Image 3: After Caulking Application and Joint Treatment h4
    'caulking-application-and-joint-treatment': [
      {
        src: '/images/modules/module-7/03_Caulking_walls_Cielings.png',
        alt: 'Caulking application at wall-to-ceiling joints showing proper bead technique and smoothing',
        caption: 'Caulking walls and ceilings: Seamless joint treatment at transitions',
      },
    ],
    // Image 4: After Finish Paint Application Systems h4
    'finish-paint-application-systems': [
      {
        src: '/images/modules/module-7/04_spray_painter.jpg',
        alt: 'Professional spray painter applying finish coat with airless sprayer showing proper technique and coverage',
        caption: 'Finish paint application: Professional spray technique for uniform coating',
      },
    ],
    // Images 5-6: Side-by-side after Trim Painting and Pre-Finishing Protocols h4
    'trim-painting-and-pre-finishing-protocols': [
      {
        src: '/images/modules/module-7/05_Caulking_Trim.png',
        alt: 'Caulking trim joints where molding meets wall surface for seamless paint-ready finish',
        caption: 'Caulking trim joints for seamless finish',
      },
      {
        src: '/images/modules/module-7/06_Spraying_Trim.png',
        alt: 'Spraying trim and millwork with finish paint for uniform professional coating',
        caption: 'Spraying trim for professional finish quality',
      },
    ],
    // Image 7: After Door and Cabinet Painting Procedures h4
    'door-and-cabinet-painting-procedures': [
      {
        src: '/images/modules/module-7/07_New_Cabinet_Install.webp',
        alt: 'New cabinet installation showing painted and finished cabinetry installed in kitchen',
        caption: 'Cabinet installation: Painted and finished cabinetry in place',
      },
    ],
    // Image 8: After Hardwood Flooring Installation Methods and Finishing h4 (floated)
    'hardwood-flooring-installation-methods-and-finishing': [
      {
        src: '/images/modules/module-7/08_Real_And_Engineered_Wood_Flooring.jpg',
        alt: 'Comparison of real hardwood and engineered wood flooring showing cross-section construction and surface appearance',
        caption: 'Real hardwood vs. engineered wood flooring comparison',
        float: 'right',
      },
    ],
  },
  8: {
    'switch-installation-and-three-way-configuration': [
      {
        src: '/images/modules/module-8/Wall_Plate_Configs.jpg',
        alt: 'Various wall plate configurations showing single, double, and triple gang switch and outlet cover plates',
        caption: 'Wall plate configurations for switch and outlet installations',
      },
      {
        src: '/images/modules/module-8/plug_installation.jpeg',
        alt: 'Electrical outlet installation showing proper wiring connections and device mounting in junction box',
        caption: 'Receptacle installation with proper terminal connections',
      },
    ],
    'lighting-fixture-installation-and-mounting': [
      {
        src: '/images/modules/module-8/ic-rated-recessed-lighting-guide-excel-cct-led-recessed-panel-light-by-dals copy.png',
        alt: 'IC-rated recessed LED panel light showing housing, trim, and ceiling integration',
        caption: 'IC-rated recessed LED panel light',
      },
      {
        src: '/images/modules/module-8/brown-magic-home-chandeliers-mh-cy-dd-385-l-64_600.jpg',
        alt: 'Decorative chandelier fixture showing mounting hardware and ceiling canopy installation',
        caption: 'Chandelier fixture installation',
      },
      {
        src: '/images/modules/module-8/recessed-lighting.webp',
        alt: 'Recessed lighting installation in ceiling showing proper spacing and trim alignment',
        caption: 'Recessed lighting layout and trim installation',
      },
    ],
    'hardwired-appliance-connections': [
      {
        src: '/images/modules/module-8/garbage-disposal-installation.webp',
        alt: 'Garbage disposal installation showing mounting assembly, electrical connection, and drain plumbing',
        caption: 'Garbage disposal: Mounting and electrical connection',
        float: 'right',
      },
    ],
    'electrical-panel-circuit-identification': [
      {
        src: '/images/modules/module-8/Labeling-breakers.jpg',
        alt: 'Electrical panel with labeled circuit breakers showing proper circuit identification and directory',
        caption: 'Circuit breaker labeling and panel directory identification',
      },
    ],
    'ground-fault-and-arc-fault-protection-verification': [
      {
        src: '/images/modules/module-8/GFC_protection_TEst.jpg',
        alt: 'GFCI protection testing using circuit tester to verify ground-fault protection at outlet',
        caption: 'GFCI protection testing and verification',
      },
      {
        src: '/images/modules/module-8/20-amp-receptacle-gfci-outlet-white-wall-plate-included__45884.webp',
        alt: '20-amp GFCI receptacle outlet with white wall plate showing test and reset buttons',
        caption: '20-amp GFCI receptacle with test/reset functionality',
      },
    ],
    'plumbing-fixture-installation-sequence-and-rough-in-verification': [
      {
        src: '/images/modules/module-8/Faucet_Install.png',
        alt: 'Faucet installation showing supply line connections, mounting hardware, and basin integration',
        caption: 'Faucet installation and supply line connections',
        float: 'right',
      },
    ],
    'toilet-installation-and-wax-ring-sealing': [
      {
        src: '/images/modules/module-8/toilet_illo-scaled.webp',
        alt: 'Toilet installation diagram showing wax ring placement, closet bolt alignment, and floor flange connection',
        caption: 'Toilet installation: Wax ring sealing and flange connection',
      },
    ],
    'sink-and-faucet-installation-procedures': [
      {
        src: '/images/modules/module-8/Sink_And_Faucet_Install.png',
        alt: 'Sink and faucet installation showing undermount sink mounting, supply connections, and drain assembly',
        caption: 'Sink and faucet installation with supply and drain connections',
        float: 'right',
      },
    ],
    'water-heater-installation-and-code-compliance': [
      {
        src: '/images/modules/module-8/Water_Heater_Install.png',
        alt: 'Water heater installation showing T&P relief valve, expansion tank, supply connections, and code-compliant venting',
        caption: 'Water heater installation with code-compliant connections',
      },
    ],
    'shower-and-tub-valve-trim-installation': [
      {
        src: '/images/modules/module-8/Shower_And_tub_Trim.webp',
        alt: 'Shower and tub valve trim installation showing escutcheon plate, handle, and diverter assembly',
        caption: 'Shower and tub valve trim installation',
      },
    ],
    'thermostat-installation-and-wiring': [
      {
        src: '/images/modules/module-8/Thermostats_Wiring.png',
        alt: 'Thermostat wiring installation showing wire color coding, terminal connections, and mounting plate',
        caption: 'Thermostat wiring and terminal connections',
        float: 'right',
      },
    ],
    'refrigerant-circuit-charging-and-startup': [
      {
        src: '/images/modules/module-8/Charging_The_HVAC_Unit.webp',
        alt: 'HVAC refrigerant charging showing manifold gauge set connected to condenser unit service valves',
        caption: 'Refrigerant circuit charging and system startup',
      },
    ],
    'airflow-measurement-and-system-balancing': [
      {
        src: '/images/modules/module-8/HVAC261_returns2_RuddVent_PNNL.jpg',
        alt: 'HVAC return air grilles and ventilation system showing proper sizing and airflow distribution',
        caption: 'Return air grilles and airflow system balancing',
      },
    ],
    'subgrade-preparation-and-vapor-barrier-installation': [
      {
        src: '/images/modules/module-8/Flatwork_Driveway_Finishes.jpg',
        alt: 'Concrete flatwork and driveway finishes showing broom finish, exposed aggregate, and stamped patterns',
        caption: 'Concrete flatwork and driveway finishing techniques',
      },
    ],
    'formwork-installation-and-reinforcement-placement': [
      {
        src: '/images/modules/module-8/concrete-construction-sidewalks.jpg',
        alt: 'Concrete sidewalk formwork installation showing form boards, stakes, reinforcement mesh, and grade preparation',
        caption: 'Sidewalk formwork and reinforcement placement',
        float: 'right',
      },
    ],
    'control-joint-layout-and-installation': [
      {
        src: '/images/modules/module-8/mc-cut-control-joints-in-concrete.jpg',
        alt: 'Control joint cutting in concrete flatwork using early-entry saw to create proper crack control joints',
        caption: 'Control joint cutting for crack prevention',
        float: 'right',
      },
    ],
    'final-grading-and-drainage-establishment': [
      {
        src: '/images/modules/module-8/drainage-around-backyard copy.png',
        alt: 'Backyard drainage system showing French drain, grading contours, and water management infrastructure',
        caption: 'Drainage system and water management',
      },
      {
        src: '/images/modules/module-8/Final_Grade.webp',
        alt: 'Final grading operations showing proper slope establishment away from foundation for drainage',
        caption: 'Final grading for proper drainage establishment',
      },
    ],
    'irrigation-system-installation': [
      {
        src: '/images/modules/module-8/sprinkler-repair-in-floyds-knobs-indiana.jpg',
        alt: 'Sprinkler head repair and adjustment showing pop-up spray head and coverage pattern',
        caption: 'Sprinkler head installation and adjustment',
      },
      {
        src: '/images/modules/module-8/Spinkler_Systerm_Installation.jpg',
        alt: 'Sprinkler system installation showing main line piping, zone valves, and head layout',
        caption: 'Sprinkler system piping and zone installation',
      },
      {
        src: '/images/modules/module-8/Irrigation.jpg',
        alt: 'Irrigation system overview showing drip lines, spray zones, and controller setup for landscape watering',
        caption: 'Complete irrigation system layout and zones',
      },
    ],
  },
  9: {
    'major-appliance-delivery-coordination': [
      {
        src: '/images/modules/module-9/Appliances.png',
        alt: 'Major appliances staged for residential installation including refrigerator, range, and dishwasher',
        caption: 'Major appliances staged for delivery and installation',
      },
      {
        src: '/images/modules/module-9/leasing-appliances.jpeg',
        alt: 'Appliance delivery and inspection process at a residential construction site',
        caption: 'Appliance receiving and inspection protocols',
      },
    ],
    'door-hardware-selection-and-standards': [
      {
        src: '/images/modules/module-9/Door Hardware.jpg',
        alt: 'Residential door hardware including lever handles, deadbolts, and hinges',
        caption: 'Door hardware selection and finish options',
      },
      {
        src: '/images/modules/module-9/download.jpeg',
        alt: 'Door hardware installation showing proper alignment and strike plate positioning',
        caption: 'Hardware installation and alignment',
      },
      {
        src: '/images/modules/module-9/dracketts.webp',
        alt: 'Premium door hardware sets with coordinated finishes for residential construction',
        caption: 'Coordinated hardware finish packages',
      },
    ],
    'cabinet-hardware-installation': [
      {
        src: '/images/modules/module-9/cabinet-knobs-pulls-lead copy.png',
        alt: 'Cabinet knobs and pulls in various styles and finishes for kitchen and bath cabinetry',
        caption: 'Cabinet knob and pull selection options',
      },
      {
        src: '/images/modules/module-9/homeguide-handyman-installing-new-cabinet-hardware.jpg',
        alt: 'Handyman installing new cabinet hardware using a drill and alignment jig',
        caption: 'Cabinet hardware installation process',
      },
      {
        src: '/images/modules/module-9/knob-installation-on-cabinet-door-with-TP-1934-Cabinet-Hardware-Jig-step-6.jpg',
        alt: 'Knob installation on cabinet door using a hardware jig for precise alignment',
        caption: 'Using a hardware jig for precise knob placement',
      },
    ],
    'paint-touch-up-strategy-and-materials-management': [
      {
        src: '/images/modules/module-9/painting.jpeg',
        alt: 'Professional paint touch-up work on interior wall surfaces',
        caption: 'Paint touch-up and materials management',
        float: 'right',
      },
    ],
    'color-verification-and-sheen-consistency': [
      {
        src: '/images/modules/module-9/Painting 2.jpeg',
        alt: 'Color verification and sheen consistency check during paint touch-up',
        caption: 'Color verification and sheen consistency',
        float: 'right',
      },
    ],
    'cleaning-phase-distinction-and-sequencing': [
      {
        src: '/images/modules/module-9/Claean 1.jpg',
        alt: 'Rough cleaning phase during construction showing debris removal and initial surface preparation',
        caption: 'Rough cleaning phase',
      },
      {
        src: '/images/modules/module-9/Clean 2.webp',
        alt: 'Final cleaning phase with detailed surface wiping and floor polishing',
        caption: 'Final cleaning phase',
      },
      {
        src: '/images/modules/module-9/Clean 3.jpeg',
        alt: 'Detail cleaning showing window washing and fixture polishing for pre-occupancy preparation',
        caption: 'Detail cleaning and pre-occupancy preparation',
      },
    ],
    'osha-compliance-in-construction-cleaning': [
      {
        src: '/images/modules/module-9/Adhering-to-CDC-OSHA-and-EPA-Cleaning-Standards.jpg',
        alt: 'CDC, OSHA, and EPA cleaning standards compliance guidelines for construction sites',
        caption: 'OSHA and EPA cleaning compliance standards',
      },
    ],
    'certificate-of-occupancy-and-final-inspections': [
      {
        src: '/images/modules/module-9/CofO Cincy.jpg',
        alt: 'Certificate of Occupancy document from Cincinnati building department',
        caption: 'Certificate of Occupancy',
        float: 'right',
        size: 'small',
      },
    ],
  },
  10: {
    'overview-the-critical-transition-from-construction-to-occupancy': [
      {
        src: '/images/modules/module-10/Law_Scale.jpg',
        alt: 'Scale of justice representing legal and regulatory aspects of construction closeout',
        caption: 'Legal framework for construction handover',
        float: 'right',
        size: 'small',
      },
    ],
    'systematic-pre-final-inspection-methodology': [
      {
        src: '/images/modules/module-10/home-building-timeline-example v2.png',
        alt: 'Home building timeline example showing inspection milestones and project phases',
        caption: 'Home building timeline and inspection milestones',
        size: 'small',
      },
    ],
    'electrical-system-completion-verification': [
      {
        src: '/images/modules/module-10/Electrical_Tester.webp',
        alt: 'Electrical testing equipment used for circuit verification and safety compliance',
        caption: 'Electrical system testing and verification',
        float: 'right',
        size: 'small',
      },
    ],
    'plumbing-system-testing-and-verification': [
      {
        src: '/images/modules/module-10/testing-water-pressure-in-your-home-2718692-04-c37ab3236d0d4b61b87079ebf9ef823e.jpg',
        alt: 'Water pressure testing gauge connected to residential plumbing system',
        caption: 'Plumbing pressure testing and verification',
        float: 'right',
        size: 'small',
      },
    ],
    'municipal-final-building-inspection-process': [
      {
        src: '/images/modules/module-10/building-inspector-pexels.jpg',
        alt: 'Building inspector conducting final inspection at a residential construction site',
        caption: 'Municipal final building inspection',
        float: 'right',
        size: 'small',
      },
    ],
    'obtaining-certificate-of-occupancy-documentation': [
      {
        src: '/images/modules/module-10/CofO Cincy.jpg',
        alt: 'Certificate of Occupancy document from Cincinnati building department',
        caption: 'Certificate of Occupancy documentation',
        float: 'right',
        size: 'small',
      },
    ],
    'hvac-system-operation-and-maintenance': [
      {
        src: '/images/modules/module-10/HVAC_Inspection.webp',
        alt: 'HVAC system inspection during residential construction',
        caption: 'HVAC Inspection',
        position: 'before',
      },
      {
        src: '/images/modules/module-10/Plumbing_Inspection.png',
        alt: 'Plumbing system inspection during residential construction',
        caption: 'Plumbing Inspection',
        position: 'before',
      },
      {
        src: '/images/modules/module-10/Electrical_Inspection.jpg',
        alt: 'Electrical system inspection during residential construction',
        caption: 'Electrical Inspection',
        position: 'before',
      },
    ],
    'plumbing-system-operation-and-maintenance': [
      {
        src: '/images/modules/module-10/Water_Heater_Inspection.jpg',
        alt: 'Water heater inspection during residential plumbing system verification',
        caption: 'Water heater inspection',
        float: 'right',
        size: 'small',
      },
    ],
    'comprehensive-lien-release-procurement': [
      {
        src: '/images/modules/module-10/Release-of-Lien-Form-1.png',
        alt: 'Release of lien form used in construction project closeout',
        caption: 'Release of Lien form',
        float: 'right',
        size: 'small',
      },
    ],
    'as-built-documentation-preparation-and-delivery': [
      {
        src: '/images/modules/module-10/As-Built_Drawings.webp',
        alt: 'As-built construction drawings showing final documentation',
        caption: 'As-built documentation',
        float: 'right',
        size: 'small',
      },
    ],
    'financial-closeout-and-final-payment-processing': [
      {
        src: '/images/modules/module-10/CM-Doing-A-Budget.webp',
        alt: 'Construction manager reviewing project budget during financial closeout',
        caption: 'Financial closeout and budget review',
        float: 'right',
        size: 'small',
      },
    ],
    'warranty-service-procedures-and-response-protocols': [
      {
        src: '/images/modules/module-10/home-warranty.jpg',
        alt: 'Home warranty documentation for post-construction coverage',
        caption: 'Home warranty coverage',
        float: 'right',
        size: 'small',
      },
    ],
  },
};